// Static theology cache — pre-written answers to foundational questions.
// These never change and never need an API call.
// Keys are lowercase normalized question strings.

const THEOLOGY_CACHE = {
  "what is the chief end of man": "Man's chief end is to glorify God and to enjoy Him forever (Westminster Shorter Catechism Q1). This is grounded in 1 Corinthians 10:31 — 'Whether you eat or drink, or whatever you do, do all to the glory of God' — and Psalm 73:25-26. The Greek word *doxa* (glory) means to display the full weight and worth of something. To glorify God is to make His character visible through how we live. The 'enjoyment' aspect reflects Augustine's insight: 'Our heart is restless until it rests in Thee.' We were made for God, and our deepest satisfaction comes from Him alone.",

  "what is god": "God is the infinite, eternal, and unchangeable Spirit — perfect in being, wisdom, power, holiness, justice, goodness, and truth (Westminster Shorter Catechism Q4). The Hebrew name *El Shaddai* (God Almighty) and *YHWH* (I AM WHO I AM, Exodus 3:14) reveal His self-existence and sufficiency. He is Trinity: one God in three co-equal, co-eternal persons — Father, Son, and Holy Spirit (Matthew 28:19). He is both transcendent (above all creation) and immanent (present within it). Deuteronomy 6:4 — 'The LORD our God, the LORD is one' — is the foundation of biblical monotheism.",

  "what is the gospel": "The Gospel (Greek: *euangelion*, 'good news') is the announcement that Jesus Christ — the eternal Son of God — took on human flesh, lived a perfectly righteous life, died on the cross as a substitutionary sacrifice for sinners, rose bodily from the dead on the third day, and now reigns as Lord. Through faith in Him, sinners receive forgiveness of sins, justification before God, and eternal life (1 Corinthians 15:1-4, Romans 1:16-17). This is not advice to follow but news to believe. The Gospel is the power of God for salvation to everyone who believes.",

  "what is justification": "Justification is the legal act of God by which He declares a sinner righteous on the basis of Christ's righteousness, received through faith alone (*sola fide*). The Greek word *dikaioo* means 'to declare righteous' — a forensic (courtroom) term. Romans 3:24 says we are 'justified freely by His grace through the redemption that is in Christ Jesus.' God does not make us righteous in justification — He *declares* us righteous. Our sins are imputed to Christ; His righteousness is imputed to us (2 Corinthians 5:21). This is the article by which the church stands or falls (Luther).",

  "what is sanctification": "Sanctification is the ongoing work of God's grace by which the believer is progressively conformed to the image of Christ (Romans 8:29). Unlike justification (a one-time declaration), sanctification is a lifelong process. The Greek *hagiasmos* means 'set apart' or 'made holy.' It involves both God's work (Philippians 2:13 — 'it is God who works in you') and human effort (Philippians 2:12 — 'work out your salvation'). Sanctification is rooted in union with Christ (Romans 6:1-14) and empowered by the Holy Spirit (Galatians 5:16-25). It will be completed at glorification.",

  "what is the trinity": "The Trinity is the doctrine that the one God eternally exists as three distinct persons — Father, Son, and Holy Spirit — each fully God, co-equal and co-eternal, yet distinct in person and role. This is not three gods (tritheism) nor one God wearing three masks (modalism), but one divine Being in three persons. Key texts: Matthew 28:19 (baptize in the *name* — singular — of Father, Son, and Spirit), John 1:1 (the Word was God), Acts 5:3-4 (lying to the Spirit = lying to God). The doctrine was formally defined at the Council of Nicaea (325 AD) against Arianism.",

  "what is repentance": "Repentance (Greek: *metanoia*, 'change of mind') is a genuine turning from sin toward God — involving the mind (acknowledging sin), the emotions (genuine sorrow, 2 Corinthians 7:10), and the will (turning away and toward God). It is not mere remorse (which Judas had, Matthew 27:3) but a complete reorientation. Acts 3:19 — 'Repent and turn back, that your sins may be blotted out.' True repentance is a gift of God (Acts 11:18, 2 Timothy 2:25) and the fruit of the Holy Spirit's conviction. It is not a one-time event but a daily posture of the Christian life (Luther's first thesis).",

  "what is saving faith": "Saving faith is more than intellectual belief (*notitia* — knowledge of the facts) or emotional assent (*assensus* — agreeing they are true). It includes *fiducia* — personal trust and reliance on Christ alone for salvation. James 2:19 notes that even demons believe (and shudder) — but they do not trust. Saving faith is the instrument by which we receive Christ and His righteousness (Ephesians 2:8-9). It is itself a gift of God, not a human work. Hebrews 11:1 defines it as 'the assurance of things hoped for, the conviction of things not seen.'",

  "what is grace": "Grace (Greek: *charis*) is God's unmerited favor toward sinners — His goodness given freely, not earned or deserved. Ephesians 2:8-9 — 'By grace you have been saved through faith, and this is not your own doing; it is the gift of God, not a result of works.' Grace is not merely God overlooking sin but His active provision of what we need at the cost of His Son. Common grace is given to all (Matthew 5:45); saving grace is given to the elect. The Reformers summarized it: *sola gratia* — grace alone is the basis of salvation.",

  "what is sin": "Sin (Hebrew: *chata*, Greek: *hamartia* — 'missing the mark') is any want of conformity to or transgression of the law of God (Westminster Shorter Catechism Q14). It includes acts of commission (doing what God forbids), omission (failing to do what God commands), and the sinful nature itself (original sin). Romans 3:23 — 'All have sinned and fall short of the glory of God.' Sin is not merely moral failure but cosmic treason — a rejection of God's authority and a distortion of His image in us. Its consequence is death (Romans 6:23) and separation from God.",

  "what is atonement": "Atonement (Hebrew: *kaphar*, 'to cover') refers to the work of Christ on the cross by which He satisfied God's justice, bore the penalty for sin, and reconciled sinners to God. Key theories: Penal Substitution (Christ bore our punishment, Isaiah 53:5-6, Romans 3:25), Propitiation (Christ satisfied God's wrath, 1 John 2:2), and Reconciliation (restoring the broken relationship, 2 Corinthians 5:18-19). The Day of Atonement (*Yom Kippur*, Leviticus 16) prefigured Christ's once-for-all sacrifice (Hebrews 9:26). The atonement is the heart of the Gospel.",

  "what is election": "Election is God's sovereign choice, made before the foundation of the world, to save certain individuals through Christ (Ephesians 1:4-5). It is unconditional — not based on foreseen faith or merit, but on God's free grace and purpose (Romans 9:11-16). The Greek *eklektos* means 'chosen out.' Election does not eliminate human responsibility — the elect are called through the preaching of the Gospel and respond in genuine faith. Reformed theology holds to unconditional election; Arminian theology holds to conditional election based on foreknown faith. Both agree election is real; they differ on its basis.",

  "what is predestination": "Predestination is God's eternal decree by which He foreordains all things that come to pass, including the salvation of His people (Romans 8:29-30 — 'those He predestined He also called; those He called He also justified'). It is broader than election (which concerns salvation specifically). The *ordo salutis* (order of salvation) in Romans 8:30 — foreknew, predestined, called, justified, glorified — shows predestination as the foundation of the believer's security. It is not fatalism (which denies human agency) but the sovereign purpose of a personal God who works through means, including human choices.",

  "what is the holy spirit": "The Holy Spirit is the third person of the Trinity — fully God, co-equal with the Father and Son (Acts 5:3-4, 2 Corinthians 3:17-18). He is not a force or influence but a person with intellect (1 Corinthians 2:10-11), will (1 Corinthians 12:11), and emotions (Ephesians 4:30). His works include: conviction of sin (John 16:8), regeneration (John 3:5-8), indwelling believers (1 Corinthians 6:19), sanctification (Galatians 5:22-23), and gifting for ministry (1 Corinthians 12). He was poured out at Pentecost (Acts 2) and now permanently indwells every believer.",

  "what is prayer": "Prayer is communion with God — the believer speaking to and listening to the living God. It includes adoration, confession, thanksgiving, and supplication (ACTS). Jesus modeled prayer in Matthew 6:9-13 (the Lord's Prayer) and taught persistence (Luke 18:1-8). The Greek *proseuchomai* implies drawing near to God. Prayer is not informing God of what He doesn't know but aligning our hearts with His will (1 John 5:14-15). It is both a privilege (Hebrews 4:16 — 'approach the throne of grace with confidence') and a command (1 Thessalonians 5:17 — 'pray without ceasing').",

  "what is baptism": "Baptism (Greek: *baptizo*, 'to immerse/wash') is the initiatory rite of the Christian faith, commanded by Christ (Matthew 28:19), signifying union with Christ in His death and resurrection (Romans 6:3-4), cleansing from sin, and membership in the covenant community. Traditions differ: Baptists practice believer's baptism by immersion; Presbyterians and Lutherans practice infant baptism as a covenant sign. All agree baptism is an outward sign of an inward reality. It does not save (1 Peter 3:21 clarifies it is 'not the removal of dirt from the body but the pledge of a clear conscience toward God').",

  "what is the lord's supper": "The Lord's Supper (Eucharist, Communion) is the ongoing ordinance instituted by Christ on the night of His betrayal (Luke 22:19-20, 1 Corinthians 11:23-26), in which believers eat bread and drink wine in remembrance of His body broken and blood shed. Views differ: Roman Catholics hold to transubstantiation (bread and wine become Christ's body and blood); Lutherans hold to consubstantiation (Christ is present 'in, with, and under' the elements); Reformed hold to spiritual presence; Baptists view it as a memorial. All agree it proclaims the Lord's death until He comes (1 Corinthians 11:26).",

  "what is the church": "The Church (Greek: *ekklesia*, 'called-out assembly') is the body of Christ — all who have been regenerated by the Holy Spirit and united to Christ by faith (Ephesians 1:22-23). The universal church includes all believers of all times and places; the local church is a visible gathering of believers for worship, teaching, fellowship, and mission (Acts 2:42-47). The church has two marks (Reformed): the Word rightly preached and the sacraments rightly administered. Some add church discipline as a third mark. The church is not a building but a people — the new covenant community.",

  "what is the bible": "The Bible (Greek: *biblia*, 'books') is the 66-book canon of Scripture — 39 Old Testament and 27 New Testament books — which Christians hold to be the inspired, inerrant, and authoritative Word of God. 2 Timothy 3:16 — 'All Scripture is God-breathed (*theopneustos*).' The Bible is the primary means by which God reveals Himself and His will. The historical-grammatical method of interpretation seeks to understand what the original authors meant in their original context. The Bible is sufficient for all matters of faith and practice (*sola scriptura*) and is its own best interpreter.",

  "what is salvation": "Salvation (Greek: *soteria*, 'deliverance, rescue') is God's comprehensive work of rescuing sinners from the penalty, power, and ultimately the presence of sin. It encompasses: justification (declared righteous), regeneration (new birth), adoption (made children of God), sanctification (made holy), and glorification (made perfect). Ephesians 2:8-9 — 'By grace you have been saved through faith.' Salvation is entirely of God — initiated by the Father (election), accomplished by the Son (atonement), and applied by the Spirit (regeneration). It is received through faith alone, in Christ alone, by grace alone.",

  "what is heaven": "Heaven is the dwelling place of God (Matthew 6:9) and the eternal home of the redeemed (John 14:2-3). The New Testament describes the final state as the 'new heaven and new earth' (Revelation 21:1) — a renewed, physical creation where God dwells with His people (Revelation 21:3). It is not a disembodied spiritual realm but a restored creation. The Greek *ouranos* can refer to the sky, the cosmos, or God's dwelling. Heaven is characterized by the absence of sin, death, mourning, and pain (Revelation 21:4) and the presence of God's glory. The intermediate state (between death and resurrection) is being 'with Christ' (Philippians 1:23).",

  "what is hell": "Hell is the place of eternal conscious punishment for those who die apart from Christ (Matthew 25:46, Revelation 20:14-15). The Greek *Gehenna* (used by Jesus 11 times) referred to the Valley of Hinnom — a place of burning refuse outside Jerusalem — used as a metaphor for final judgment. Hell is described as 'eternal fire' (Matthew 25:41), 'outer darkness' (Matthew 8:12), and 'the second death' (Revelation 20:14). It is the just consequence of rejecting God and His offer of salvation. Annihilationism (the wicked cease to exist) and universalism (all are eventually saved) are minority views rejected by historic orthodoxy.",

  "what is the resurrection": "The resurrection is the bodily raising of the dead at the end of the age. Christ's resurrection (1 Corinthians 15:3-8) is the firstfruits and guarantee of the believer's resurrection (1 Corinthians 15:20-23). The Greek *anastasis* means 'standing up again.' The resurrection body is physical but transformed — imperishable, glorious, powerful, spiritual (1 Corinthians 15:42-44). The resurrection is not the immortality of the soul (a Greek concept) but the redemption of the whole person — body and soul. Without the resurrection, Paul says, 'your faith is futile' (1 Corinthians 15:17). It is the cornerstone of Christian hope.",

  "what is the second coming": "The Second Coming (Greek: *parousia*, 'presence/arrival') is the promised return of Jesus Christ in glory to judge the living and the dead, resurrect the dead, and establish His eternal kingdom (Acts 1:11, Matthew 24:30, Revelation 19:11-16). Unlike His first coming in humility, He will return in power and great glory. Views on the timing and sequence differ (premillennialism, amillennialism, postmillennialism), but all orthodox Christians affirm the literal, bodily, visible return of Christ. It is the 'blessed hope' of the church (Titus 2:13) and the consummation of redemptive history.",

  "what is the kingdom of god": "The Kingdom of God is the reign and rule of God — His sovereign authority exercised over all creation, and specifically over His redeemed people. Jesus announced 'The kingdom of God is at hand' (Mark 1:15) — it arrived in His person and ministry. The Kingdom is both 'already' (present in Christ's first coming, Luke 17:21) and 'not yet' (consummated at His return, Revelation 11:15). It is entered through repentance and faith (Mark 1:15), not ethnicity or religious performance. The Kingdom is the central theme of Jesus' teaching and the goal of redemptive history.",

  "what is covenant": "A covenant (Hebrew: *berith*, Greek: *diatheke*) is a solemn, binding agreement between God and His people, establishing relationship and defining obligations. Key biblical covenants: Noahic (Genesis 9), Abrahamic (Genesis 12, 15, 17), Mosaic/Sinai (Exodus 19-24), Davidic (2 Samuel 7), and New Covenant (Jeremiah 31:31-34, Luke 22:20). The New Covenant, inaugurated by Christ's blood, fulfills and supersedes the Mosaic covenant. Covenant theology sees all of Scripture as unified by God's covenant relationship with His people — the thread running from creation to new creation.",

  "what is the law of god": "The Law of God refers to God's moral standard revealed in Scripture, summarized in the Ten Commandments (Exodus 20) and the two great commandments (Matthew 22:37-40). The Law has three uses (Reformed): civil (restraining evil in society), pedagogical (revealing sin and driving us to Christ, Galatians 3:24), and normative (guiding the believer's life). The Law cannot save — 'by works of the law no human being will be justified' (Romans 3:20) — but it reveals God's character and our need for grace. Christ fulfilled the Law perfectly (Matthew 5:17) and His righteousness is credited to believers.",

  "who is jesus": "Jesus of Nazareth is the eternal Son of God who took on human flesh (John 1:14 — *the Word became flesh*). He is fully God and fully man — two natures in one person (the hypostatic union, defined at Chalcedon 451 AD). His names reveal His identity: *Jesus* (Hebrew: *Yeshua*, 'YHWH saves'), *Christ* (Greek: *Christos*, 'Anointed One' = Messiah). He was born of a virgin (Isaiah 7:14, Matthew 1:23), lived without sin (Hebrews 4:15), died as a substitutionary sacrifice, rose bodily on the third day, ascended to the Father's right hand, and will return in glory. He is Prophet, Priest, and King.",

  "what is the incarnation": "The Incarnation (Latin: *in carne*, 'in flesh') is the eternal Son of God taking on a full human nature — body, soul, and spirit — while remaining fully divine. John 1:14 — 'The Word became flesh and dwelt among us.' The Greek *sarx* (flesh) emphasizes the reality of His humanity. He was not a divine being appearing human (Docetism) nor a human elevated to divinity (Adoptionism) but truly God and truly man. The Council of Chalcedon (451 AD) defined: one person, two natures, without confusion, change, division, or separation. The Incarnation was necessary for the atonement — only a sinless human could die for humans.",

  "what is the sermon on the mount": "The Sermon on the Mount (Matthew 5-7) is Jesus' foundational ethical teaching, delivered early in His ministry. It begins with the Beatitudes (Matthew 5:3-12) — describing the character of Kingdom citizens — and covers topics including anger, lust, divorce, oaths, retaliation, love of enemies, prayer (the Lord's Prayer, 6:9-13), fasting, wealth, anxiety, and judgment. Jesus repeatedly says 'You have heard... but I say to you' — not abolishing the Law but revealing its deeper intent (Matthew 5:17-20). The Sermon describes life in the Kingdom, not a means of earning salvation. It exposes our need for grace.",

  "what does romans 8:28 mean": "Romans 8:28 — 'And we know that for those who love God all things work together for good, for those who are called according to his purpose' (ESV) — is one of the most cited promises in Scripture. The Greek *synergei* ('work together') is a compound word meaning all things cooperate toward a single end. The 'good' is not comfort or ease but conformity to Christ (v.29 — 'conformed to the image of his Son'). The promise is for 'those who love God' and 'are called' — the elect. It does not say all things are good, but that God sovereignly works all things — including suffering — toward His redemptive purpose.",

  "what is john 3:16": "John 3:16 — 'For God so loved the world, that he gave his only Son, that whoever believes in him should not perish but have eternal life' — is the Gospel in miniature. The Greek *houtōs* ('so') means 'in this way' — describing the manner of God's love, not merely its intensity. *Agape* (love) is self-giving, sacrificial love. *Monogenes* ('only begotten/unique') emphasizes the Son's unique relationship to the Father. 'The world' (*kosmos*) refers to humanity in its fallen state. 'Perish' (*apollymi*) means eternal destruction. 'Eternal life' (*zōē aiōnios*) is not just endless existence but the life of the age to come — knowing God (John 17:3).",

  "what is ephesians 2:8-9": "Ephesians 2:8-9 — 'For by grace you have been saved through faith. And this is not your own doing; it is the gift of God, not a result of works, so that no one may boast' — is the clearest statement of salvation by grace alone through faith alone. The Greek perfect tense *sesōsmenoi* ('you have been saved') indicates a completed action with ongoing results. The 'gift of God' likely refers to the entire salvation package (grace + faith), not faith alone. 'Not of works' directly contradicts any merit-based system. The purpose: 'so that no one may boast' — all glory goes to God. Verse 10 adds that we are saved *for* good works, not *by* them.",

  "what is the great commission": "The Great Commission (Matthew 28:18-20) is Christ's final command to His disciples: 'Go therefore and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit, teaching them to observe all that I have commanded you.' The main verb is *mathēteusate* ('make disciples') — not merely converts. The authority behind the commission: 'All authority in heaven and on earth has been given to me.' The scope: 'all nations' (*panta ta ethnē* — all people groups). The promise: 'I am with you always, to the end of the age.' This is the mission of the church until Christ returns.",

  "what is the great commandment": "The Great Commandment (Matthew 22:37-40) is Jesus' summary of the entire Law: 'You shall love the Lord your God with all your heart and with all your soul and with all your mind. This is the great and first commandment. And a second is like it: You shall love your neighbor as yourself. On these two commandments depend all the Law and the Prophets.' The first (from Deuteronomy 6:5) addresses our vertical relationship with God; the second (from Leviticus 19:18) addresses our horizontal relationship with others. All 613 commandments of the Mosaic Law hang on these two principles.",

  "what is discipleship": "Discipleship (Greek: *mathētēs*, 'learner/follower') is the process of becoming and making followers of Jesus Christ. A disciple is not merely a student of information but an apprentice of a way of life — learning to think, feel, and act like Jesus. Luke 9:23 — 'If anyone would come after me, let him deny himself and take up his cross daily and follow me.' Discipleship involves: learning the Word (Matthew 4:4), prayer (Luke 11:1), community (Acts 2:42-47), mission (Matthew 28:19-20), and suffering (Philippians 3:10). It is lifelong, costly, and the normal expectation for every believer — not just the spiritually advanced.",

  "what is worship": "Worship (Hebrew: *shachah*, 'to bow down'; Greek: *proskuneō*, 'to kiss toward') is the response of the whole person — mind, heart, will, and body — to the worth (*weorthscipe*, Old English root of 'worship') of God. John 4:24 — 'God is spirit, and those who worship him must worship in spirit and truth.' True worship is not limited to singing but encompasses all of life (Romans 12:1 — 'present your bodies as a living sacrifice... this is your spiritual worship'). Corporate worship (gathering of the church) and personal worship (daily devotion) are both essential. The Regulative Principle (Reformed) holds that worship should include only what God commands.",

  "what is the fear of the lord": "The fear of the Lord (Hebrew: *yirat YHWH*) is the foundational posture of wisdom and right relationship with God. Proverbs 9:10 — 'The fear of the LORD is the beginning of wisdom.' It is not terror (*phobos* in the negative sense) but reverent awe — a deep recognition of God's holiness, majesty, and authority that shapes all of life. Ecclesiastes 12:13 — 'Fear God and keep his commandments, for this is the whole duty of man.' The fear of the Lord produces: wisdom (Proverbs 1:7), hatred of evil (Proverbs 8:13), confidence (Proverbs 14:26), and life (Proverbs 19:23). It is the antidote to the fear of man.",
};

// Normalize a question for cache lookup
function normalizeQuestion(q) {
  return q.toLowerCase()
    .replace(/[^a-z0-9\s]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

// Find a cached answer — exact match or close match
function findCachedAnswer(question) {
  const normalized = normalizeQuestion(question);
  
  // Exact match
  if (THEOLOGY_CACHE[normalized]) return THEOLOGY_CACHE[normalized];
  
  // Partial match — check if question contains a key or key contains question words
  const words = normalized.split(' ').filter(w => w.length > 3);
  for (const [key, answer] of Object.entries(THEOLOGY_CACHE)) {
    const keyWords = key.split(' ');
    const matchCount = words.filter(w => keyWords.includes(w)).length;
    if (matchCount >= 3 || (words.length <= 4 && matchCount >= 2)) {
      return answer;
    }
  }
  
  return null;
}

module.exports = { findCachedAnswer };
